// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import rsdb "github.com/realsangil/apimonitor/pkg/rsdb"
import rsmodel "github.com/realsangil/apimonitor/pkg/rsmodel"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: tx, src
func (_m *Repository) Create(tx rsdb.Transaction, src rsmodel.ValidatedObject) error {
	ret := _m.Called(tx, src)

	var r0 error
	if rf, ok := ret.Get(0).(func(rsdb.Transaction, rsmodel.ValidatedObject) error); ok {
		r0 = rf(tx, src)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateTable provides a mock function with given fields: tx
func (_m *Repository) CreateTable(tx rsdb.Transaction) error {
	ret := _m.Called(tx)

	var r0 error
	if rf, ok := ret.Get(0).(func(rsdb.Transaction) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteById provides a mock function with given fields: tx, id
func (_m *Repository) DeleteById(tx rsdb.Transaction, id rsmodel.ValidatedObject) error {
	ret := _m.Called(tx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(rsdb.Transaction, rsmodel.ValidatedObject) error); ok {
		r0 = rf(tx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FirstOrCreate provides a mock function with given fields: tx, src
func (_m *Repository) FirstOrCreate(tx rsdb.Transaction, src rsmodel.ValidatedObject) error {
	ret := _m.Called(tx, src)

	var r0 error
	if rf, ok := ret.Get(0).(func(rsdb.Transaction, rsmodel.ValidatedObject) error); ok {
		r0 = rf(tx, src)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetById provides a mock function with given fields: tx, id
func (_m *Repository) GetById(tx rsdb.Transaction, id rsmodel.ValidatedObject) error {
	ret := _m.Called(tx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(rsdb.Transaction, rsmodel.ValidatedObject) error); ok {
		r0 = rf(tx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: tx, items, filter, orders
func (_m *Repository) List(tx rsdb.Transaction, items interface{}, filter rsdb.ListFilter, orders rsdb.Orders) (int, error) {
	ret := _m.Called(tx, items, filter, orders)

	var r0 int
	if rf, ok := ret.Get(0).(func(rsdb.Transaction, interface{}, rsdb.ListFilter, rsdb.Orders) int); ok {
		r0 = rf(tx, items, filter, orders)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(rsdb.Transaction, interface{}, rsdb.ListFilter, rsdb.Orders) error); ok {
		r1 = rf(tx, items, filter, orders)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Patch provides a mock function with given fields: tx, src, data
func (_m *Repository) Patch(tx rsdb.Transaction, src rsmodel.ValidatedObject, data rsmodel.ValidatedObject) error {
	ret := _m.Called(tx, src, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(rsdb.Transaction, rsmodel.ValidatedObject, rsmodel.ValidatedObject) error); ok {
		r0 = rf(tx, src, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: tx, src
func (_m *Repository) Save(tx rsdb.Transaction, src rsmodel.ValidatedObject) error {
	ret := _m.Called(tx, src)

	var r0 error
	if rf, ok := ret.Get(0).(func(rsdb.Transaction, rsmodel.ValidatedObject) error); ok {
		r0 = rf(tx, src)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
