environment: 'development'
db:
  host: 'apimonitor.db'
  port: 3306
  username: 'root'
  password: '1234'
  name: 'apimonitor'
  verbose: true
logger:
  level: 'debug'
  format: 'text'
  output: 'console'
  path: ''
