# 엔드포인트 생성
POST {{apiAddr}}/{{apiVersion}}/webservices/{{WebServiceId}}/endpoints
Content-Type: application/json

{
  "path": "test/post",
  "http_method": "DELETE",
  "content_type": "application/json",
  "request_data": null,
  "header": null,
  "query_param": null
}
###

# 엔드포인트 조회
GET {{apiAddr}}/{{apiVersion}}/endpoints/{{EndpointId}}
Content-Type: application/json

###

# 엔드포인트 삭제
DELETE {{apiAddr}}/{{apiVersion}}/endpoints/{{EndpointId}}
Content-Type: application/json

###

# 엔드포인트 리스트
GET {{apiAddr}}/{{apiVersion}}/endpoints?web_service_id={{WebServiceId}}
Content-Type: application/json

###
