# 웹서비스 생성
POST {{apiAddr}}/{{apiVersion}}/webservices
Content-Type: application/json

{
  "host": "http://admin.lalaworks.com",
  "desc": "test api",
  "favicon": ""
}

###

# 웹서비스 리스트 조회
GET {{apiAddr}}/{{apiVersion}}/webservices
Content-Type: application/json

###

# 웹서비스 조회
GET {{apiAddr}}/{{apiVersion}}/webservices/{{WebServiceId}}
Content-Type: application/json

###

# 웹서비스 삭제
DELETE {{apiAddr}}/{{apiVersion}}/webservices/{{WebServiceId}}
Content-Type: application/json

###

# 웹서비스 수정
PUT {{apiAddr}}/{{apiVersion}}/webservices/{{WebServiceId}}
Content-Type: application/json

{
  "host": "https://realsangil.github.io",
  "desc": "sangil's blog",
  "favicon": "www.lalaworks.com/favicon.png"
}

###
