POST {{apiAddr}}/{{apiVersion}}/webservices
Content-Type: application/json

{
  "host": "http://vidoc.lalaworks.com",
  "desc": "test api"
}

###

GET {{apiAddr}}/{{apiVersion}}/webservices/{{web_service_id}}
Content-Type: application/json

###
