// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ScheduleRefresher is an autogenerated mock type for the ScheduleRefresher type
type ScheduleRefresher struct {
	mock.Mock
}

// Init provides a mock function with given fields:
func (_m *ScheduleRefresher) Init() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
