// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import amerr "github.com/realsangil/apimonitor/pkg/amerr"
import mock "github.com/stretchr/testify/mock"
import models "github.com/realsangil/apimonitor/models"
import rsmodels "github.com/realsangil/apimonitor/pkg/rsmodels"

// TestResultService is an autogenerated mock type for the TestResultService type
type TestResultService struct {
	mock.Mock
}

// GetResultListByTestId provides a mock function with given fields: test, request
func (_m *TestResultService) GetResultListByTestId(test *models.Test, request models.TestResultListRequest) (*rsmodels.PaginatedList, *amerr.ErrorWithLanguage) {
	ret := _m.Called(test, request)

	var r0 *rsmodels.PaginatedList
	if rf, ok := ret.Get(0).(func(*models.Test, models.TestResultListRequest) *rsmodels.PaginatedList); ok {
		r0 = rf(test, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rsmodels.PaginatedList)
		}
	}

	var r1 *amerr.ErrorWithLanguage
	if rf, ok := ret.Get(1).(func(*models.Test, models.TestResultListRequest) *amerr.ErrorWithLanguage); ok {
		r1 = rf(test, request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*amerr.ErrorWithLanguage)
		}
	}

	return r0, r1
}
