// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import amerr "github.com/realsangil/apimonitor/pkg/amerr"
import mock "github.com/stretchr/testify/mock"
import models "github.com/realsangil/apimonitor/models"
import rsmodels "github.com/realsangil/apimonitor/pkg/rsmodels"

// TestService is an autogenerated mock type for the TestService type
type TestService struct {
	mock.Mock
}

// CreateTest provides a mock function with given fields: webService, request
func (_m *TestService) CreateTest(webService *models.WebService, request models.TestRequest) (*models.Test, *amerr.ErrorWithLanguage) {
	ret := _m.Called(webService, request)

	var r0 *models.Test
	if rf, ok := ret.Get(0).(func(*models.WebService, models.TestRequest) *models.Test); ok {
		r0 = rf(webService, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Test)
		}
	}

	var r1 *amerr.ErrorWithLanguage
	if rf, ok := ret.Get(1).(func(*models.WebService, models.TestRequest) *amerr.ErrorWithLanguage); ok {
		r1 = rf(webService, request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*amerr.ErrorWithLanguage)
		}
	}

	return r0, r1
}

// DeleteTestById provides a mock function with given fields: endpoint
func (_m *TestService) DeleteTestById(endpoint *models.Test) *amerr.ErrorWithLanguage {
	ret := _m.Called(endpoint)

	var r0 *amerr.ErrorWithLanguage
	if rf, ok := ret.Get(0).(func(*models.Test) *amerr.ErrorWithLanguage); ok {
		r0 = rf(endpoint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*amerr.ErrorWithLanguage)
		}
	}

	return r0
}

// GetTestById provides a mock function with given fields: endpoint
func (_m *TestService) GetTestById(endpoint *models.Test) *amerr.ErrorWithLanguage {
	ret := _m.Called(endpoint)

	var r0 *amerr.ErrorWithLanguage
	if rf, ok := ret.Get(0).(func(*models.Test) *amerr.ErrorWithLanguage); ok {
		r0 = rf(endpoint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*amerr.ErrorWithLanguage)
		}
	}

	return r0
}

// GetTestList provides a mock function with given fields: request
func (_m *TestService) GetTestList(request models.TestListRequest) (*rsmodels.PaginatedList, *amerr.ErrorWithLanguage) {
	ret := _m.Called(request)

	var r0 *rsmodels.PaginatedList
	if rf, ok := ret.Get(0).(func(models.TestListRequest) *rsmodels.PaginatedList); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rsmodels.PaginatedList)
		}
	}

	var r1 *amerr.ErrorWithLanguage
	if rf, ok := ret.Get(1).(func(models.TestListRequest) *amerr.ErrorWithLanguage); ok {
		r1 = rf(request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*amerr.ErrorWithLanguage)
		}
	}

	return r0, r1
}
