// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	amerr "github.com/realsangil/apimonitor/pkg/amerr"
	mock "github.com/stretchr/testify/mock"

	models "github.com/realsangil/apimonitor/models"

	rsmodel "github.com/realsangil/apimonitor/pkg/rsmodels"
)

// WebServiceTestService is an autogenerated mock type for the WebServiceTestService type
type WebServiceTestService struct {
	mock.Mock
}

// CreateWebServiceTest provides a mock function with given fields: webService, request
func (_m *WebServiceTestService) CreateWebServiceTest(webService *models.WebService, request models.WebServiceTestRequest) (*models.WebServiceTest, *amerr.ErrorWithLanguage) {
	ret := _m.Called(webService, request)

	var r0 *models.WebServiceTest
	if rf, ok := ret.Get(0).(func(*models.WebService, models.WebServiceTestRequest) *models.WebServiceTest); ok {
		r0 = rf(webService, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.WebServiceTest)
		}
	}

	var r1 *amerr.ErrorWithLanguage
	if rf, ok := ret.Get(1).(func(*models.WebService, models.WebServiceTestRequest) *amerr.ErrorWithLanguage); ok {
		r1 = rf(webService, request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*amerr.ErrorWithLanguage)
		}
	}

	return r0, r1
}

// DeleteWebServiceTestById provides a mock function with given fields: endpoint
func (_m *WebServiceTestService) DeleteWebServiceTestById(endpoint *models.WebServiceTest) *amerr.ErrorWithLanguage {
	ret := _m.Called(endpoint)

	var r0 *amerr.ErrorWithLanguage
	if rf, ok := ret.Get(0).(func(*models.WebServiceTest) *amerr.ErrorWithLanguage); ok {
		r0 = rf(endpoint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*amerr.ErrorWithLanguage)
		}
	}

	return r0
}

// GetWebServiceTestById provides a mock function with given fields: endpoint
func (_m *WebServiceTestService) GetWebServiceTestById(endpoint *models.WebServiceTest) *amerr.ErrorWithLanguage {
	ret := _m.Called(endpoint)

	var r0 *amerr.ErrorWithLanguage
	if rf, ok := ret.Get(0).(func(*models.WebServiceTest) *amerr.ErrorWithLanguage); ok {
		r0 = rf(endpoint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*amerr.ErrorWithLanguage)
		}
	}

	return r0
}

// GetWebServiceTestList provides a mock function with given fields: request
func (_m *WebServiceTestService) GetWebServiceTestList(request models.WebServiceTestListRequest) (*rsmodel.PaginatedList, *amerr.ErrorWithLanguage) {
	ret := _m.Called(request)

	var r0 *rsmodel.PaginatedList
	if rf, ok := ret.Get(0).(func(models.WebServiceTestListRequest) *rsmodel.PaginatedList); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rsmodel.PaginatedList)
		}
	}

	var r1 *amerr.ErrorWithLanguage
	if rf, ok := ret.Get(1).(func(models.WebServiceTestListRequest) *amerr.ErrorWithLanguage); ok {
		r1 = rf(request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*amerr.ErrorWithLanguage)
		}
	}

	return r0, r1
}
